# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_user', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('admin_pwd', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('stu_name', models.CharField(max_length=128)),
                ('stu_photo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('sum_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.IntegerField(max_length=16)),
                ('interaction', models.IntegerField(max_length=128)),
                ('grade', models.IntegerField(max_length=128)),
                ('course_time', models.IntegerField(max_length=128)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Course')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('teacher_name', models.CharField(max_length=128)),
                ('teacher_pwd', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='selection',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Student'),
        ),
    ]
