# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-15 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190115_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
